name: lembra_vencimentos
description: App para lembrar vencimentos (RG, CNH, carteirinhas) — aviso local
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  flutter_local_notifications: ^17.2.3
  intl: ^0.18.0
  timezone: ^0.9.0
  uuid: ^4.5.1
  supabase_flutter: ^2.5.1
  image_picker: ^1.0.7
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/calendar_bell.svg
